name: PR Comment

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          url=$(curl https://shibe.online/api/shibes | jq -r '.[0]')
          cat <<EOF > comment-body.md
          ![]($url)
          https://shibe.online/
          EOF

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: github-actions[bot]
          body-includes: https://shibe.online/

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: comment-body.md
          edit-mode: replace
